"""installations

Revision ID: cefcdd72570f
Revises: 
Create Date: 2026-08-30 18:03:28.219360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefcdd72570f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=False),
    sa.Column('machine_fingerprint', sa.String(length=80), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('nom_agence', sa.String(length=150), nullable=True),
    sa.Column('hostname', sa.String(length=150), nullable=True),
    sa.Column('os_info', sa.String(length=120), nullable=True),
    sa.Column('email_contact', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('essai', 'actif', 'suspendu', name='statutinstallation'), nullable=False),
    sa.Column('essai_expire_le', sa.DateTime(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installations_installation_id'), ['installation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_installations_machine_fingerprint'), ['machine_fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installations_machine_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_installations_installation_id'))

    op.drop_table('installations')
    # ### end Alembic commands ###
