"""etat des lieux (depart retour)

Revision ID: 0a903bb471f1
Revises: 8961eb860fe4
Create Date: 2026-09-02 03:30:00.119852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a903bb471f1'
down_revision = '8961eb860fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etats_des_lieux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('depart', 'retour', name='typeetatdeslieux'), nullable=False),
    sa.Column('date_effectue', sa.DateTime(), nullable=False),
    sa.Column('kilometrage', sa.Integer(), nullable=True),
    sa.Column('niveau_carburant', sa.Enum('vide', 'quart', 'moitie', 'trois_quarts', 'plein', name='niveaucarburant'), nullable=True),
    sa.Column('degats', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'type', name='uq_etat_reservation_type')
    )
    with op.batch_alter_table('etats_des_lieux', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etats_des_lieux_reservation_id'), ['reservation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etats_des_lieux', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etats_des_lieux_reservation_id'))

    op.drop_table('etats_des_lieux')
    # ### end Alembic commands ###
