"""suivi de caution (statut, retenue, note)

Revision ID: 30e0b3e1a715
Revises: 6b8612148c79
Create Date: 2026-09-02 03:07:59.815618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e0b3e1a715'
down_revision = '6b8612148c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caution_statut', sa.Enum('non_recue', 'recue', 'restituee', 'retenue', name='statutcaution'), server_default='non_recue', nullable=False))
        batch_op.add_column(sa.Column('caution_retenue', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('caution_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('caution_note')
        batch_op.drop_column('caution_retenue')
        batch_op.drop_column('caution_statut')

    # ### end Alembic commands ###
