"""facture TVA + identifiants legaux agence (ICE RC IF patente)

Revision ID: 4be92b09da41
Revises: 5f06e20d7408
Create Date: 2026-09-02 02:37:44.405016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be92b09da41'
down_revision = '5f06e20d7408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ice', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('rc', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('identifiant_fiscal', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('patente', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('tva_applicable', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), server_default='20', nullable=False))

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('montant_tva', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('taux_tva', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_column('taux_tva')
        batch_op.drop_column('montant_tva')
        batch_op.drop_column('montant_ht')

    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.drop_column('taux_tva')
        batch_op.drop_column('tva_applicable')
        batch_op.drop_column('patente')
        batch_op.drop_column('identifiant_fiscal')
        batch_op.drop_column('rc')
        batch_op.drop_column('ice')

    # ### end Alembic commands ###
