"""agence.langue (i18n)

Revision ID: 5f06e20d7408
Revises: 77c99bd7683d
Create Date: 2026-09-01 02:20:39.664093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f06e20d7408'
down_revision = '77c99bd7683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('langue', sa.String(length=2), server_default='fr', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.drop_column('langue')

    # ### end Alembic commands ###
