"""echeances vehicule (assurance visite technique vignette vidange)

Revision ID: 6b8612148c79
Revises: 4be92b09da41
Create Date: 2026-09-02 02:45:38.326868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8612148c79'
down_revision = '4be92b09da41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assurance_expire_le', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('visite_technique_expire_le', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vignette_expire_le', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('prochaine_vidange_le', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('prochaine_vidange_km', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.drop_column('prochaine_vidange_km')
        batch_op.drop_column('prochaine_vidange_le')
        batch_op.drop_column('vignette_expire_le')
        batch_op.drop_column('visite_technique_expire_le')
        batch_op.drop_column('assurance_expire_le')

    # ### end Alembic commands ###
