"""contrat location: permis client, caution reservation, conditions agence

Revision ID: 77c99bd7683d
Revises: da193eb91268
Create Date: 2026-09-01 01:45:38.709192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c99bd7683d'
down_revision = 'da193eb91268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conditions_contrat', sa.Text(), nullable=True))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_permis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_delivrance_permis', sa.Date(), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caution', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('lieu_prise_en_charge', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('lieu_prise_en_charge')
        batch_op.drop_column('caution')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('date_delivrance_permis')
        batch_op.drop_column('numero_permis')

    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.drop_column('conditions_contrat')

    # ### end Alembic commands ###
