"""heures de depart et de retour sur la reservation

Revision ID: 8961eb860fe4
Revises: 30e0b3e1a715
Create Date: 2026-09-02 03:13:11.845713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8961eb860fe4'
down_revision = '30e0b3e1a715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure_debut', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('heure_fin', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('heure_fin')
        batch_op.drop_column('heure_debut')

    # ### end Alembic commands ###
