"""objectif CA agence, canal acquisition reservation, depenses vehicule

Revision ID: d19a1f274c4a
Revises: 0a903bb471f1
Create Date: 2026-09-02 04:34:48.332206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19a1f274c4a'
down_revision = '0a903bb471f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depenses_vehicule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('achat', 'assurance', 'entretien', 'reparation', 'credit', 'autre', name='typedepense'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_depense', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('depenses_vehicule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depenses_vehicule_vehicule_id'), ['vehicule_id'], unique=False)

    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectif_ca_mensuel', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Enum('agence', 'telephone', 'whatsapp', 'site_web', 'partenaire', name='sourcereservation'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('agence', schema=None) as batch_op:
        batch_op.drop_column('objectif_ca_mensuel')

    with op.batch_alter_table('depenses_vehicule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depenses_vehicule_vehicule_id'))

    op.drop_table('depenses_vehicule')
    # ### end Alembic commands ###
