"""Migration initiale : User, Client, Vehicule, Reservation, Facture, Agence

Revision ID: da193eb91268
Revises: 
Create Date: 2026-08-09 22:14:28.861571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da193eb91268'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('mentions_legales', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('type_piece_identite', sa.Enum('cni', 'passeport', name='typepieceidentite'), nullable=True),
    sa.Column('numero_piece_identite', sa.String(length=50), nullable=True),
    sa.Column('document_identite_url', sa.String(length=255), nullable=True),
    sa.Column('permis_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'employe', name='roleuser'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=80), nullable=False),
    sa.Column('modele', sa.String(length=80), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('couleur', sa.String(length=50), nullable=True),
    sa.Column('kilometrage', sa.Integer(), nullable=True),
    sa.Column('carburant', sa.Enum('essence', 'diesel', 'hybride', 'electrique', name='carburant'), nullable=True),
    sa.Column('transmission', sa.Enum('manuelle', 'automatique', name='transmission'), nullable=True),
    sa.Column('tarif_jour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('disponible', 'loue', 'maintenance', 'hors_service', name='statutvehicule'), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicules_immatriculation'), ['immatriculation'], unique=True)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('en_attente', 'confirmee', 'en_cours', 'terminee', 'annulee', name='statutreservation'), nullable=False),
    sa.Column('prix_jour_applique', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('numero_facture', sa.String(length=30), nullable=False),
    sa.Column('date_emission', sa.DateTime(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut_paiement', sa.Enum('en_attente', 'payee', 'annulee', name='statutpaiement'), nullable=False),
    sa.Column('mode_paiement', sa.Enum('especes', 'carte', 'virement', 'cheque', name='modepaiement'), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id')
    )
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factures_numero_facture'), ['numero_facture'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factures_numero_facture'))

    op.drop_table('factures')
    op.drop_table('reservations')
    with op.batch_alter_table('vehicules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicules_immatriculation'))

    op.drop_table('vehicules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('clients')
    op.drop_table('agence')
    # ### end Alembic commands ###
